# Generated by Django 3.1.3 on 2020-11-19 10:01

import Projecteam.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projectdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('member', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=4)),
                ('status', models.BooleanField(default=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Projecteam.models.nameing)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projecteam.projectdb')),
            ],
        ),
    ]
